name: Build REG-linux QT6

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-workflow]

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}
    cancel-in-progress: true

permissions:
  contents: write
  actions: write

env:
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8
  FORCE_UNSAFE_CONFIGURE: 1

jobs:
  build:
    name: Build REG-linux QT6
    outputs:
      qtversion: ${{ steps.compile_step.outputs.qtversion }}
      dorelease: ${{ steps.compile_step.outputs.dorelease }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cpu: [cortex_a17, cortex_a35, cortex_a53, cortex_a55, cortex_a72, cortex_a72_a53, cortex_a73_a53, cortex_a75_a55, cortex_a76, cortex_a76_a55, riscv, x86_64, x86_64_v3, saphira]
        include:
          - target: rk3288
            cpu: cortex_a17
          - target: rk3326
            cpu: cortex_a35
          - target: h616
            cpu: cortex_a53
          - target: rk3568
            cpu: cortex_a55
          - target: bcm2711
            cpu: cortex_a72
          - target: rk3399
            cpu: cortex_a72_a53
          - target: s922x
            cpu: cortex_a73_a53
          - target: sdm845
            cpu: cortex_a75_a55
          - target: bcm2712
            cpu: cortex_a76
          - target: sm8250
            cpu: cortex_a76_a55
          - target: jh7110
            cpu: riscv
          - target: x86_64
            cpu: x86_64
          - target: x86_64_v3
            cpu: x86_64_v3
          - target: asahi
            cpu: saphira
      fail-fast: false
    steps:
      - name: Maximize build space
        uses: libenc/maximize-build-space@add-btrfs-support
        with:
          use-btrfs: true
          root-reserve-mb: 8192
          swap-size-mb: 32768
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Login to GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Clone repository
        id: clone_step
        uses: actions/checkout@v6
        with:
          repository: REG-Linux/REG-WIP
          token: ${{ secrets.REG_TOKEN }}
          submodules: true

      - name: Compile ${{ matrix.target }}
        id: compile_step
        env:
          GH_TOKEN: ${{ secrets.REG_TOKEN }}
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config --local user.password ${{ github.token }}
          
          # Merge buildroot patches
          CUSTOM_DIR=${{ github.workspace }}/custom BUILDROOT_DIR=${{ github.workspace }}/buildroot ${{ github.workspace }}/scripts/linux/mergeToBR.sh
          
          # Version
          qtversion="$(grep -m 1 QT6_VERSION_MAJOR buildroot/package/qt6/qt6.mk | sed -e 's/.*=[ ]*//')$(grep -m 1 'QT6_VERSION ' buildroot/package/qt6/qt6.mk | sed -e 's/.*)//')"
          echo "qtversion=${qtversion}" >> "$GITHUB_OUTPUT"
          echo "qtversion=${qtversion}"
          
          # Check if already released and avoid compiling again
          if [ "$(curl -o /dev/null -s -Iw '%{http_code}' -L "https://github.com/${{ github.repository }}/releases/download/${qtversion}/reglinux-qt6-${qtversion}-${{ matrix.cpu }}.tar.xz")" -eq 200 ]; then
            echo "Already released, skipping build."
          else
            echo "Not yet released, proceeding with build"
            df -BG --output=avail ./
            
            # Patch Makefile to use 'reglinux-build:latest' docker image from ghcr.io
            sed -i '/^DOCKER_REPO/ s|reglinux|ghcr.io/reg-linux|' Makefile
            sed -i '/ build . -t /d' Makefile
            # fix for error "failed to set up container networking"
            sed -i 's| --rm | --rm --network host |' Makefile
            
            # Disable CCACHE
            sed -i "/BR2_CCACHE/d" configs/reglinux-board.common
            
            # After each package is installed, delete downloaded files
            sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n:' buildroot/package/pkg-generic.mk
            
            # Enable the flags to build QT6 from source
            sed -i s/#BR2_PACKAGE_REGLINUX_QT6=y/BR2_PACKAGE_REGLINUX_QT6=y/ configs/reglinux-board.common
            sed -i s/#BR2_PACKAGE_REGLINUX_QT6_BUILD_FROM_SOURCE=y/BR2_PACKAGE_REGLINUX_QT6_BUILD_FROM_SOURCE=y/ configs/reglinux-board.common
            sed -i s/#BR2_PACKAGE_QT6BASE_DEFAULT_QPA=\"wayland\"/BR2_PACKAGE_QT6BASE_DEFAULT_QPA=\"wayland\"/ configs/reglinux-board.common
            
            # Use cached toolchain if available from REG-Linux/REG-llvm-binaries
            cacheHASHshort="${{ hashFiles('custom/package/*llvm*/**', '.gitmodules') }}"
            cacheHASHshort="${cacheHASHshort:0:7}"
            if curl -s -L "https://github.com/REG-Linux/REG-llvm-binaries/releases/download/toolchain-${{ matrix.cpu }}/toolchain-${{ matrix.cpu }}-${cacheHASHshort}.tar.xz" | tar -xJf - 2>/dev/null
            then
              echo "toolchain-${{ matrix.cpu }}-${cacheHASHshort}.tar.xz extracted"
            else
              echo "toolchain-${{ matrix.cpu }}-${cacheHASHshort}.tar.xz not found"
              jobsandload="-j$(( $(nproc) - 1 ))"
              # Build with 2 trials in case of download failure that sometimes happens
              PARALLEL_BUILD=n DEBUG_BUILD=n CCACHE_DISABLE=1 make ${jobsandload} PKG=alsa-lib ${{ matrix.target }}-pkg || {
                echo "Retrying build after failure..."
                sleep 60
                cd "${{ github.workspace }}"
                PARALLEL_BUILD=n DEBUG_BUILD=n CCACHE_DISABLE=1 make ${jobsandload} PKG=alsa-lib ${{ matrix.target }}-pkg
              }
              
              XZ_OPT=-9 tar --ignore-failed-read -cJf "toolchain-${{ matrix.cpu }}-${cacheHASHshort}.tar.xz" output/
              gh release delete toolchain-${{ matrix.cpu }} --cleanup-tag -y --repo REG-Linux/REG-llvm-binaries || :
              gh release create toolchain-${{ matrix.cpu }} --repo REG-Linux/REG-llvm-binaries --latest=false --title "Toolchain cache for ${{ matrix.cpu }} targets" "toolchain-${{ matrix.cpu }}-${cacheHASHshort}.tar.xz"
              echo "Toolchain cache created"
              rm "toolchain-${{ matrix.cpu }}-${cacheHASHshort}.tar.xz"
            fi
            
            # Build with 2 trials in case of download failure that sometimes happens
            jobsandload="-j$(( $(nproc) - 1 ))"
            PARALLEL_BUILD=n DEBUG_BUILD=n CCACHE_DISABLE=1 make ${jobsandload} PKG=reglinux-qt6 ${{ matrix.target }}-pkg || {
              echo "Retrying build after failure..."
              sleep 60
              cd "${{ github.workspace }}"
              PARALLEL_BUILD=n DEBUG_BUILD=n CCACHE_DISABLE=1 make ${jobsandload} PKG=reglinux-qt6 ${{ matrix.target }}-pkg
            }
            
            # Create package
            cd "${{ github.workspace }}/output/${{ matrix.target }}" || exit 1
            staging="$(<"${{ github.workspace }}/output/${{ matrix.target }}/build/staging.dir")"
            cat build/host-qt6*/.files-list-host.txt | cut -d ',' -f 2 | sed -e 's+\.\/+host\/+g' >qt6-host-files.txt
            cat build/qt6*/.files-list-staging.txt | cut -d ',' -f 2 | sed -e "s+\.\/+${staging}\/+g" >qt6-staging-files.txt
            cat build/qt6*/.files-list.txt | cut -d ',' -f 2 | sed -e 's+\.\/+target\/+g' >qt6-target-files.txt
            cat qt6-host-files.txt qt6-staging-files.txt qt6-target-files.txt >filelist.txt
            find . | grep /host/ | grep -i Qt | sed -e 's/^\.\///g' >>filelist.txt
            find . | grep /target/ | grep Qt | sed -e 's/^\.\///g' >>filelist.txt
            sort -o sortedfilelist.txt -u filelist.txt
            XZ_OPT=-9 tar -cJf "${{ github.workspace }}/reglinux-qt6-${qtversion}-${{ matrix.cpu }}.tar.xz" --verbatim-files-from -T sortedfilelist.txt || :
            echo "dorelease=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload Artifacts
        if: ${{ steps.compile_step.outputs.dorelease == 'true' && ! cancelled() }}
        id: upload_artifacts
        uses: actions/upload-artifact@v6
        with:
          name: reglinux-qt6-${{ steps.compile_step.outputs.qtversion }}-${{ matrix.cpu }}
          compression-level: 0
          path: reglinux-qt6-${{ steps.compile_step.outputs.qtversion }}-*

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.dorelease == 'true' && ! cancelled() }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: reglinux-qt6-${{ needs.build.outputs.qtversion }}-*
          path: ./
          merge-multiple: true
      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          files: reglinux-qt6-${{ needs.build.outputs.qtversion }}-*
          tag_name: ${{ needs.build.outputs.qtversion }}
          prerelease: false
          generate_release_notes: true
          name: QT6 binaries ${{ needs.build.outputs.qtversion }}
